import type { Metadata } from "next";
import Sidebar from "./_components/sidebar";
import { Inter } from "next/font/google";

import "./globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "auto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.className} antialiased`}>
        <div className="flex h-full gap-4">
          <Sidebar />
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
